"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var order_controller_1 = require("../controllers/order.controller");
var auth_middleware_1 = require("../middlewares/auth.middleware");
var router = (0, express_1.Router)();
router.post("/", auth_middleware_1.verifyAccessToken, auth_middleware_1.requireClient, order_controller_1.OrdersController.create);
router.get("/mine", auth_middleware_1.verifyAccessToken, auth_middleware_1.requireClient, order_controller_1.OrdersController.listMine);
router.get("/", auth_middleware_1.verifyAccessToken, auth_middleware_1.requireAdmin, order_controller_1.OrdersController.listAll);
router.get("/mine/:id", auth_middleware_1.verifyAccessToken, auth_middleware_1.requireClient, order_controller_1.OrdersController.getByIdClient);
router.get("/:id", auth_middleware_1.verifyAccessToken, auth_middleware_1.requireAdmin, order_controller_1.OrdersController.getByIdAdmin);
exports.default = router;
