apiVersion: apps/v1
kind: Deployment
metadata:
  name: categories
  namespace: mercadoverde
spec:
  replicas: 2
  selector:
    matchLabels:
      app: categories
  template:
    metadata:
      labels:
        app: categories
    spec:
      containers:
        - name: categories
          image: elviflo/mercadoverde-categories:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              valueFrom: { configMapKeyRef: { name: common-env, key: NODE_ENV } }
            - name: PORT
              value: "3004"
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-categories-svc:5432/$(POSTGRES_DB)?schema=public"
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: postgres-categories-secret, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-categories-secret, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: postgres-categories-secret, key: POSTGRES_DB } }
          readinessProbe:
            httpGet: { path: "/health", port: 3004 }
            initialDelaySeconds: 8
          livenessProbe:
            httpGet: { path: "/health", port: 3004 }
            initialDelaySeconds: 20
