apiVersion: v1
kind: Service
metadata:
  name: categories-svc
  namespace: mercadoverde
spec:
  type: ClusterIP
  selector:
    app: categories
  ports:
    - name: http
      port: 80
      targetPort: 3004
