apiVersion: v1
kind: Service
metadata:
  name: orders-svc
  namespace: mercadoverde
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: http
      port: 80
      targetPort: 3002
