services:
  auth:
    build:
      context: ./auth
    container_name: auth_service
    ports:
      - "3001:3001"
    env_file:
      - ./auth/.env
    depends_on:
      - db

  orders:
    build:
      context: ./orders
    container_name: orders_service
    ports:
      - "3002:3002"
    env_file:
      - ./orders/.env
    depends_on:
      - db

  products:
    build:
      context: ./products
    container_name: products_service
    ports:
      - "3003:3003"
    env_file:
      - ./products/.env
    depends_on:
      - db

  cart:
    build:
      context: ./cart
    container_name: cart_service
    ports:
      - "3004:3002"
    env_file:
      - ./cart/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: microservices_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: microservices
    ports:
      - "5433:5432"
