apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  namespace: mercadoverde
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: elviflo/mercadoverde-products:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              valueFrom: { configMapKeyRef: { name: common-env, key: NODE_ENV } }
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-products-svc:5432/$(POSTGRES_DB)?schema=public"
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: postgres-products-secret, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-products-secret, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: postgres-products-secret, key: POSTGRES_DB } }
          readinessProbe:
            httpGet: { path: "/health", port: 3003 }
            initialDelaySeconds: 8
          livenessProbe:
            httpGet: { path: "/health", port: 3003 }
            initialDelaySeconds: 20
