apiVersion: v1
kind: Service
metadata:
  name: products-svc
  namespace: mercadoverde
spec:
  type: ClusterIP
  selector:
    app: products
  ports:
    - name: http
      port: 80
      targetPort: 3003
