apiVersion: v1
kind: Secret
metadata:
  name: postgres-voice-secret
  namespace: mercadoverde
type: Opaque
stringData:
  POSTGRES_USER: voice_user
  POSTGRES_PASSWORD: voice_pass
  POSTGRES_DB: voice_db
