apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice
  namespace: mercadoverde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice
  template:
    metadata:
      labels:
        app: voice
    spec:
      containers:
        - name: voice
          image: elviflo/mercadoverde-voice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3006
          env:
            - name: NODE_ENV
              valueFrom: { configMapKeyRef: { name: common-env, key: NODE_ENV } }
            - name: PORT
              value: "3006"
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-voice-svc:5432/$(POSTGRES_DB)?schema=public"
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: postgres-voice-secret, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: postgres-voice-secret, key: POSTGRES_PASSWORD } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: postgres-voice-secret, key: POSTGRES_DB } }
          readinessProbe:
            httpGet: { path: "/health", port: 3006 }
            initialDelaySeconds: 8
          livenessProbe:
            httpGet: { path: "/health", port: 3006 }
            initialDelaySeconds: 20
