apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-svc
  namespace: mercadoverde
spec:
  type: ClusterIP
  selector:
    app: postgres-auth
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
