apiVersion: v1
kind: Secret
metadata:
  name: postgres-products-secret
  namespace: mercadoverde
type: Opaque
stringData:
  POSTGRES_USER: products_user
  POSTGRES_PASSWORD: products_pass
  POSTGRES_DB: products_db
